/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.Sender;
import bl.SenderTableModel;
import bl.SenderTableRenderer;

/**
 *
 * @author Dominik
 */
public class SenderGUI extends javax.swing.JFrame {
    private SenderTableModel bl = new SenderTableModel();
    /**
     * Creates new form SenderGUI
     */
    public SenderGUI() {
        initComponents();
        table.setModel(bl);
        table.setDefaultRenderer(Object.class, new SenderTableRenderer());
        
        bl.add(new Sender("Oe3", 194.20, "FM"));
        bl.add(new Sender("Antenne", 70.10, "FM"));
        bl.add(new Sender("Radio A1", 120.60, "AM"));
        
        bl.sort();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmPopup = new javax.swing.JPopupMenu();
        miHinzufügen = new javax.swing.JMenuItem();
        miHide = new javax.swing.JMenuItem();
        miShow = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        miHinzufügen.setText("Hinzufügen");
        miHinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHinzufügenActionPerformed(evt);
            }
        });
        pmPopup.add(miHinzufügen);

        miHide.setText("Band Verstecken");
        miHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHideActionPerformed(evt);
            }
        });
        pmPopup.add(miHide);

        miShow.setText("Band Anzeigen");
        miShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miShowActionPerformed(evt);
            }
        });
        pmPopup.add(miShow);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.setComponentPopupMenu(pmPopup);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miHinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHinzufügenActionPerformed
        SenderDialog dl = new SenderDialog(this,true);
        dl.setVisible(true);
        
        if(dl.isOk()){
            Sender s = dl.getSender();
            bl.add(s);
            bl.sort();
        }
    }//GEN-LAST:event_miHinzufügenActionPerformed

    private void miHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHideActionPerformed
        bl.numCols(2);
    }//GEN-LAST:event_miHideActionPerformed

    private void miShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miShowActionPerformed
        bl.numCols(3);
    }//GEN-LAST:event_miShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SenderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miHide;
    private javax.swing.JMenuItem miHinzufügen;
    private javax.swing.JMenuItem miShow;
    private javax.swing.JPopupMenu pmPopup;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
